Fix wrong bottle name
Address: https://github.com/ustclug/discussions/issues/232
Related: https://github.com/Homebrew/brew/pull/4612

err log:
curl: (22) The requested URL returned error: 404 Not Found
Error: wrong number of arguments (given 1, expected 2)
/root/.linuxbrew/Library/Homebrew/exceptions.rb:543:in `block in initialize'
/root/.linuxbrew/Library/Homebrew/exceptions.rb:552:in `map'
/root/.linuxbrew/Library/Homebrew/exceptions.rb:552:in `initialize'
/root/.linuxbrew/Library/Homebrew/system_command.rb:101:in `new'
/root/.linuxbrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/root/.linuxbrew/Library/Homebrew/system_command.rb:46:in `run!'
/root/.linuxbrew/Library/Homebrew/system_command.rb:23:in `run'
/root/.linuxbrew/Library/Homebrew/system_command.rb:27:in `run!'
/root/.linuxbrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/root/.linuxbrew/Library/Homebrew/utils/curl.rb:43:in `curl'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:37:in `block (2 levels) in <top (required)>'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:16:in `each'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:16:in `block in <top (required)>'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:3:in `each'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:3:in `<top (required)>'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/root/.linuxbrew/Library/Homebrew/utils.rb:19:in `require?'
/root/.linuxbrew/Library/Homebrew/brew.rb:95:in `<main>'